### ISSUE TITLE
Feature: Apply bone names to armature

### ISSUE THREAD

**Issue by dreamsyntax** [Psycrow101/Blender-3D-STH-Mtn-plugin#2]
While this plugin is more accurate than the 3DSMax equivalent, the two bone sets make this a bit complicated for use in projects.

![image](https://user-images.githubusercontent.com/14857235/234980286-8bea0886-77fa-4261-a60e-94cbb30512f9.png)

A mode where the bone names are applied to the actual armature that controls the model and the unused names are not saved would be useful. I am a novice when it comes to blender, is there a particular reason its applied to a separate armature than the one with the model?

### Example of current behavior:

![image](https://user-images.githubusercontent.com/14857235/234980788-06de44f1-ee95-4fba-b311-58c588be5c5a.png)

The named bones will not have any affect on the model. The unnamed modify the model.

### Desired behavior:

The named bones are directly in the main armature. Moving si2_j_kosi or any named bone modify the model.

![image](https://user-images.githubusercontent.com/14857235/234981326-e33d0473-9f22-4d63-b43a-23f980caf937.png)

**Comment by Psycrow101** [comment]
@dreamsyntax Greetings. I've updated the addon to add the option to apply bone names to an armature.
https://github.com/Psycrow101/Blender-3D-STH-Mtn-plugin/releases/download/0.0.4/io_scene_sth_mtn.zip

An additional hierarchy of bones is required for the correct export of the animation to mtn. Keyframes in the mtn animation contain the values of positions and rotations of the bones separately. In addition, the animation contains bezier curve values. This makes it very difficult to import the animation into Blender since positioning in the original armature takes a completely different approach. Working directly with the original armature can result in a huge animation file size after export. Therefore, it is necessary to come up with an optimal algorithm to solve this problem, but this will take a lot of time. Maybe I'll do it in the future.

If there is no need to export the animation back to mtn, then you can use "Bake action" option and remove the BON hierarchy. This way it will be possible to safely export the animation to another game, such as Sonic Heroes.

Have a good day

**Comment by dreamsyntax** [comment]
Awesome, thanks for working on that!

Thanks for clarifying the 'why' for the armature. I am a very blender inexperienced.
