### ISSUE TITLE
Bug: MTN Stretch Applied to Wrong Area

### ISSUE THREAD

**Issue by dreamsyntax** [Psycrow101/Blender-3D-STH-Mtn-plugin#5]
It seems the stretch is applied to the wrong skin or wrong bone (I am not sure).
Example is most of Sonic jump related animations. Other models/mtns are affected too, but I think these are great to use as an example as its clear what is wrong.

The head is stretching rather than the body
![image](https://github.com/Psycrow101/Blender-3D-STH-Mtn-plugin/assets/14857235/03e462be-4be4-4806-8b55-cb07ea4e8e38)

![image](https://github.com/Psycrow101/Blender-3D-STH-Mtn-plugin/assets/14857235/9af21c0b-e727-4a4d-b148-d4c17fc89926)

Blender-3D-STH-Mtn-plugin Output:
https://github.com/Psycrow101/Blender-3D-STH-Mtn-plugin/assets/14857235/cc92b942-c0f3-48fb-9a42-f57e2d4aba30

Expected Output/Game Output:
https://github.com/Psycrow101/Blender-3D-STH-Mtn-plugin/assets/14857235/baac3f12-f950-45b4-adec-5d27a8c24091

I have attached the pre-animation apply .blend and the above shown very clear wrong stretch animation in .blend form
[mtn-stretch-issue.zip](https://github.com/Psycrow101/Blender-3D-STH-Mtn-plugin/files/12806214/mtn-stretch-issue.zip)

**Comment by Psycrow101** [comment]
Apparently I misinterpreted how scaling works in this game. I think this can be fixed, but the behavior of node transformations will change, since the scaling in Blender is clearly different from what is presented in the game. I'll think about how to make the correct scaling and conveniently control it in the editor.

**Comment by dreamsyntax** [comment]
Just realized I did not include the mtns themselves.
Adding them here.

[sonic_mtn_selected.zip](https://github.com/Psycrow101/Blender-3D-STH-Mtn-plugin/files/12809205/sonic_mtn_selected.zip)


> Apparently I misinterpreted how scaling works in this game. I think this can be fixed, but the behavior of node transformations will change, since the scaling in Blender is clearly different from what is presented in the game. I'll think about how to make the correct scaling and conveniently control it in the editor.

Does this mean the dragonff import part will change? Or just the .bon / mtn portion?

**Comment by Psycrow101** [comment]
Instead of empty objects there will be separate armature.

I've almost fixed the scaling. Can I ask you to check this animation in the game? I need to see how the bones will behave to make the export more accurate.

[sn_jump_a.zip](https://github.com/Psycrow101/Blender-3D-STH-Mtn-plugin/files/12832492/sn_jump_a.zip)

**Comment by dreamsyntax** [comment]
> Instead of empty objects there will be separate armature.
> 
> I've almost fixed the scaling. Can I ask you to check this animation in the game? I need to see how the bones will behave to make the export more accurate.
> 
> [sn_jump_a.zip](https://github.com/Psycrow101/Blender-3D-STH-Mtn-plugin/files/12832492/sn_jump_a.zip)

It looks like the original preview
![image](https://github.com/Psycrow101/Blender-3D-STH-Mtn-plugin/assets/14857235/d5c88908-7367-43d2-aea8-a686d094d413)

video:

https://github.com/Psycrow101/Blender-3D-STH-Mtn-plugin/assets/14857235/5eca2e0f-911c-438f-aa2f-2d14a1f89953

**Comment by Psycrow101** [comment]
> video:

Thanks!

I updated the addon and now the scaling works correctly. Instead of empty objects, a separate armature is used with additional parameters for bones. Unfortunately, additional bones had to be added to the BON armature, but they are hidden in the viewport by default. A new property is available to control advanced scaling options (Bon Scale).

![image](https://github.com/Psycrow101/Blender-3D-STH-Mtn-plugin/assets/31922454/b4806ba5-9ac7-41b5-adeb-9b2a92ce9141)

Baking into the original armature may not work correctly, but overall the transformations looks fine.

Also added batch import feature for MTN.

**Comment by dreamsyntax** [comment]
Unless I'm missing something, I'm getting wildly incorrect results now.
I completely started with a fresh DFF, imported BON with updated plugin, import MTN with updated plugin.

I also do not see the batch import
![image](https://github.com/Psycrow101/Blender-3D-STH-Mtn-plugin/assets/14857235/7ffa05af-a199-48b5-9a70-680c3e536353)


Update: Just realized I had multi-mesh version of DragonFF in Blender. Perhaps it would be better to have those as two separate plugins if they can never be merged for compatibility reasons?

**Comment by Psycrow101** [comment]
Try the latest version of multi-mesh

**Comment by dreamsyntax** [comment]
Works fine with latest main Parik27 DragonFF:
![image](https://github.com/Psycrow101/Blender-3D-STH-Mtn-plugin/assets/14857235/0f9f147c-34a1-429b-ae7d-fbfec1891406)


Latest multi-mesh:
![image](https://github.com/Psycrow101/Blender-3D-STH-Mtn-plugin/assets/14857235/153dc6e3-8462-42f6-bd57-4f325fb7d1aa)


Both work good 👍
